# Generated by Django 3.2.19 on 2023-06-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название тега')),
                ('color', models.CharField(max_length=7, verbose_name='цвет тега')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='url адрес для тега на английском')),
            ],
            options={
                'verbose_name': 'тег',
            },
        ),
    ]
