# Generated by Django 3.2.19 on 2023-06-13 11:25

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, validators=[recipes.validators.validate_recipe_name], verbose_name='Название рецепта'),
        ),
    ]
