# Generated by Django 3.2 on 2023-05-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230521_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_time',
            new_name='cooking_time',
        ),
    ]
